server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: SERVICE-FLOW-APP

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: ${database.user}
    password: ${database.pass}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: debug
#    org.zalando.logbook: trace
#    com.saimonfill.repairhistoryapi.repository: error
#    com.saimonfill.repairhistoryapi.service: error

# todo: change secret key to a real one
jwt:
  secret: uTbO6Gyfh6pdPG8uhMtaQjml/lBICm7Ga3CrWx9KxnMMbFFUIbMn7B1pQC5T37Sa1zgesGezOP17DLIiRyJdRw==