server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /api/repair/v1
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: REPAIR-HISTORY-API
    version: 0.0.1-SNAPSHOT

  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}
    username: ${database.user}
    password: ${database.pass}
    tomcat:
      max-active: 2
      max-idle: 1
      initial-size: 2
      max-wait: 700
      jmx-enabled: false
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: debug
    org.zalando.logbook: trace
    com.saimonfill.repairhistoryapi.repository: error
    com.saimonfill.repairhistoryapi.service: error

# todo: change secret key to a real one
jwt:
  secret: uTbO6Gyfh6pdPG8uhMtaQjml/lBICm7Ga3CrWx9KxnMMbFFUIbMn7B1pQC5T37Sa1zgesGezOP17DLIiRyJdRw==